<a href="https://colab.research.google.com/github/sasumwen/tensorflow-developer-certificate_ZTM/blob/next/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this Notebook, we cover the most fundamemntal concepts of tensors using tensorFlow 

We cover
* intro to tensors
* getting info from tnesors
* manipulating tensors
* tensors and numpy
* using @tf.function(a way to speed up regular python functions)
* using GPU's with tensorflow(or tpu)
* execrises

## Introduction to Tensors

In [67]:
# import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.9.2


In [68]:
#  Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [69]:
#  check the numbr of dimensions of a tensor (ndim stands for number of dimentsions)
scalar.ndim

0

In [70]:
# create a vector 
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [71]:
#  check the vect ndim
vector.ndim

1

In [72]:
# create a matric (more than one dimension)
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [73]:
matrix.ndim

2

In [74]:
#  create another matrix
another_one = tf.constant([[10.,7],
                           [3,2],
                           [8,9.]], dtype=tf.float16) # specifying the data type

In [75]:
another_one

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [76]:
another_one.ndim

2

In [77]:
#  create a tennsor
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                     [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [78]:
tensor.ndim

3

What we createed so far
* scalar: a single number
* vector: a number with dimension
* matrix:  a 2 dimension array of number
* tensor: an n dimnesion array of number 

# creating tensors with tf.variable

In [79]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

In [80]:
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [81]:
# for variable tensor, you can change the element using the .assign()
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Creating random tensors

In [82]:
# create two random (but same ) tensors
random_1 = tf.random.Generator.from_seed(84) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.65641224, -2.286797  ],
       [ 0.07126775,  2.3546813 ],
       [ 2.2539537 , -0.8510308 ]], dtype=float32)>

### Shuffling the order of elements in a tensor

In [83]:
#  shuffle a tensor (ideal for when you want to shuffle your data so the inherent oredr dossnt affect learning)
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [84]:
tf.random.set_seed(84)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

### Other ways to make tebsors

In [85]:
# Create a tensor of ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [86]:
# create a tensor of all  zeros
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### you can also turn numpy arrays into tensorflow tensors

the amin diff ntw numpy arrays and tensorflow is that tf can be run on a gpu for pfaster computing

In [87]:
import numpy as np
numpy_A = np.arange(1,25, dtype = np.int32) # create a numpy arrays btw 1 and 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [88]:
A = tf.constant(numpy_A, shape= (2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting information from tensors
* Shape
* Rank
* Axis or dimension
* Size

In [89]:
# create a rank 4 tensor (4 dimension)
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor 

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

### indexing tensors

tensors can be indexed just like python lists

In [90]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [91]:
# get the first element from each dimentsiin from each index except the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [92]:
# create a rank_2 tensor (2 dimension)
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [93]:
# get the last item of each row of the rank2
rank_2_tensor[-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>

In [94]:
# add in extra dimension of rank 2 
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [95]:
# alternatibe to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

## Manipulating tensors(tensor operations)

Basic Ops

In [96]:
# you can add values to a tenssor using the addition operator
tensor = tf.constant([[10,7],
                     [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [97]:
#  multi
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [98]:
#  we can also use the tf built in functions
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [99]:
# or
tf.math.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

### Matrix multiplication

in ML, matrix mult is one of the most common ops

In [100]:
print(tensor)
tf.linalg.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [101]:
# matrix mult using python operator
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [102]:
#  create a a tensor of 3X2
X = tf.constant([[1,2],
                 [3,4],
                [5,6]])

#  another
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [103]:
#  note that the above tensor cant multi 
# refer to matrix mult rules (only when matrix 1 column is equal to matrix 2 row)

# lets reshape tensor Y
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [104]:
#  mult x by reshape(y)
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [105]:
#  can do the same it transpose


** the dot product **
Matrix multiplication  is also referred to as the dot python

can be performed using
* tf.matmul()
* tf.tensordot()

### Changing the data type of a tensor

In [106]:
# create a new tensoor with the deault datatype (float32)
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [107]:
# chanege from float 32 to float 16 (reduce precison)
B = tf.cast(B, dtype=tf.float16)
B


<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

### Aggregating tensors

Aggregating ytensots mean condensing them from multiple vsalurd down to smaller amount of values

In [108]:
# get the absolute values
D =tf.constant([-7, -10])
D, tf.abs(D)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>)

Various forms of aggregaating tensors
* get the minimum
* get the maximum
* get the mean of a tensor
* get the sum of  a tensor


In [109]:
# create a random tensor with values btw 0 and a 100 of size 50
E =tf.constant(np.random.randint(0,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([32, 61, 86, 57, 33, 55, 43, 11, 29, 66, 23, 56, 26, 19, 18,  0, 38,
       69, 42, 69, 95, 53, 24, 50, 91, 17, 84,  8, 63, 76, 62, 87, 93, 17,
       36, 16, 97, 82, 87, 25, 41, 94, 66, 21, 48, 49, 19, 42, 22, 32])>

In [110]:
#  find the min
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [111]:
# find the max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [112]:
# find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [113]:
# find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2430>

In [114]:
# variance
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=731.12>

In [115]:
# STD
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.03923>

### finding the positional max and min

In [116]:
#  create a new tensor for finfing miiiiiiiiiiin anf max
tf.random.set_seed(84)
F = tf.random.uniform(shape=[50])
F


<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6752322 , 0.07654727, 0.17704082, 0.4875176 , 0.59420335,
       0.22550237, 0.9895787 , 0.11397505, 0.76960266, 0.9109514 ,
       0.9022031 , 0.88879526, 0.8251649 , 0.8076726 , 0.37604678,
       0.08291662, 0.08010626, 0.64241993, 0.44362867, 0.54224133,
       0.06212544, 0.49427843, 0.22530258, 0.5357063 , 0.6136848 ,
       0.9981259 , 0.8462304 , 0.0899297 , 0.7671411 , 0.02064371,
       0.17759812, 0.31149256, 0.3833078 , 0.09686565, 0.7968019 ,
       0.73487616, 0.22700477, 0.9049419 , 0.43215597, 0.7176515 ,
       0.57811046, 0.9545188 , 0.9585389 , 0.45191896, 0.60023403,
       0.8077353 , 0.39500773, 0.8875952 , 0.03515244, 0.53597975],
      dtype=float32)>

In [117]:
#  finf the positional max
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=25>

In [118]:
# index on the largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9981259>

In [119]:
# find the max val of F
tf.reduce_max(F)


<tf.Tensor: shape=(), dtype=float32, numpy=0.9981259>

In [120]:
# check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Squeezing a tensor
(removing all single dimensions)

In [121]:
# create a tensor to get startee
tf.random.set_seed(84)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6752322 , 0.07654727, 0.17704082, 0.4875176 , 0.59420335,
           0.22550237, 0.9895787 , 0.11397505, 0.76960266, 0.9109514 ,
           0.9022031 , 0.88879526, 0.8251649 , 0.8076726 , 0.37604678,
           0.08291662, 0.08010626, 0.64241993, 0.44362867, 0.54224133,
           0.06212544, 0.49427843, 0.22530258, 0.5357063 , 0.6136848 ,
           0.9981259 , 0.8462304 , 0.0899297 , 0.7671411 , 0.02064371,
           0.17759812, 0.31149256, 0.3833078 , 0.09686565, 0.7968019 ,
           0.73487616, 0.22700477, 0.9049419 , 0.43215597, 0.7176515 ,
           0.57811046, 0.9545188 , 0.9585389 , 0.45191896, 0.60023403,
           0.8077353 , 0.39500773, 0.8875952 , 0.03515244, 0.53597975]]]]],
      dtype=float32)>

In [122]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6752322 , 0.07654727, 0.17704082, 0.4875176 , 0.59420335,
       0.22550237, 0.9895787 , 0.11397505, 0.76960266, 0.9109514 ,
       0.9022031 , 0.88879526, 0.8251649 , 0.8076726 , 0.37604678,
       0.08291662, 0.08010626, 0.64241993, 0.44362867, 0.54224133,
       0.06212544, 0.49427843, 0.22530258, 0.5357063 , 0.6136848 ,
       0.9981259 , 0.8462304 , 0.0899297 , 0.7671411 , 0.02064371,
       0.17759812, 0.31149256, 0.3833078 , 0.09686565, 0.7968019 ,
       0.73487616, 0.22700477, 0.9049419 , 0.43215597, 0.7176515 ,
       0.57811046, 0.9545188 , 0.9585389 , 0.45191896, 0.60023403,
       0.8077353 , 0.39500773, 0.8875952 , 0.03515244, 0.53597975],
      dtype=float32)>

### onehot encode tensors

In [123]:
# create a list of index
some_list = [0,1,2,3]

# onehot encode
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

### tensors and numpy

tensorflow interacts beautifully woith np arrays


In [124]:
# create a tensor directly from a numpy array
J = tf.constant(np.array([3., 7., 10]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [125]:
# convert the tensor back to np array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [126]:
# convert tensor j tp np
J.numpy()

array([ 3.,  7., 10.])

In [127]:
tf.test.gpu_device_name()


''

In [128]:
tf.config.list_physical_devices(

)

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [129]:
tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

## 00. TensorFlow Fundamentals Exercises

In [130]:
#  create a scalar
S = tf.constant(84)
S

<tf.Tensor: shape=(), dtype=int32, numpy=84>

In [131]:
# create a vector
V = tf.constant([8,4])
V

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([8, 4], dtype=int32)>

In [132]:
# create a matrix
M = tf.constant(
                  [
                    [1,2,3],
                    [4,5,6]
                  ] 
                )
M

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [133]:
# create a tensor
T = tf.constant(
                  [
                      [
                          [1,2,3],
                          [4,5,6],
                          [7,8,9]
                      ],
                      [
                          [10,11,12],
                          [13,14,15],
                          [16,17,18]
                      ]
                  ]
              )
T

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [134]:
# find the shape rank and size of anbove
T.shape, tf.size(T), tf.rank(T)

(TensorShape([2, 3, 3]),
 <tf.Tensor: shape=(), dtype=int32, numpy=18>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>)

In [136]:
#  create 2 random tensor withrandom values between 0 and 1 and shape [5,300]
tf.random.set_seed(84)
T_1 = tf.random.uniform(shape=(5,300))
T_2 = tf.random.uniform(shape=(5,300))

T_1, T_2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.6752322 , 0.07654727, 0.17704082, ..., 0.268494  , 0.93460405,
         0.3753606 ],
        [0.9812459 , 0.4030409 , 0.78762996, ..., 0.5793381 , 0.04866922,
         0.08849216],
        [0.75825715, 0.97082734, 0.4777218 , ..., 0.52746844, 0.34301555,
         0.7303269 ],
        [0.7023028 , 0.34554017, 0.9634563 , ..., 0.7319186 , 0.88437426,
         0.15069425],
        [0.9195274 , 0.2414136 , 0.57870185, ..., 0.22874153, 0.44089305,
         0.14483345]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.27287972, 0.590515  , 0.14443886, ..., 0.6666846 , 0.6532706 ,
         0.44531775],
        [0.32082045, 0.14317882, 0.8037497 , ..., 0.42554772, 0.973721  ,
         0.11952055],
        [0.76799667, 0.25024438, 0.4353248 , ..., 0.80579615, 0.10865402,
         0.25200713],
        [0.30935073, 0.0494473 , 0.7057109 , ..., 0.5979935 , 0.8347089 ,
         0.5607066 ],
        [0.92615

In [139]:
tf.linalg.matmul(T_1,tf.transpose(T_2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.06811 , 71.79557 , 68.84199 , 76.02257 , 71.109314],
       [76.55557 , 76.57701 , 75.6698  , 83.136055, 73.82795 ],
       [77.15427 , 72.155205, 74.29129 , 79.89113 , 71.722855],
       [74.59848 , 77.280594, 74.19986 , 80.11245 , 73.32687 ],
       [75.50911 , 73.116684, 71.83657 , 77.63481 , 74.59829 ]],
      dtype=float32)>

In [140]:
tf.tensordot(T_1, tf.transpose(T_2), axes =1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.06811 , 71.79557 , 68.84199 , 76.02257 , 71.109314],
       [76.55557 , 76.57701 , 75.6698  , 83.136055, 73.82795 ],
       [77.15427 , 72.155205, 74.29129 , 79.89113 , 71.722855],
       [74.59848 , 77.280594, 74.19986 , 80.11245 , 73.32687 ],
       [75.50911 , 73.116684, 71.83657 , 77.63481 , 74.59829 ]],
      dtype=float32)>

In [142]:
tf.random.set_seed(84)

Tens = tf.random.uniform(shape=[224, 224, 3], minval=0, maxval=1)
Tens

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.6752322 , 0.07654727, 0.17704082],
        [0.4875176 , 0.59420335, 0.22550237],
        [0.9895787 , 0.11397505, 0.76960266],
        ...,
        [0.4037621 , 0.87882197, 0.8535689 ],
        [0.74307156, 0.76431596, 0.05897355],
        [0.31973147, 0.64556324, 0.89521575]],

       [[0.1428591 , 0.7044561 , 0.79638183],
        [0.30525684, 0.75169957, 0.63695073],
        [0.04601395, 0.33755004, 0.87047887],
        ...,
        [0.59219384, 0.25473487, 0.29891777],
        [0.6661869 , 0.15304983, 0.1611427 ],
        [0.6344396 , 0.05122876, 0.54145265]],

       [[0.9645407 , 0.72902787, 0.64514124],
        [0.8970641 , 0.84972525, 0.9090797 ],
        [0.3946023 , 0.7519753 , 0.6998576 ],
        ...,
        [0.13360894, 0.6293855 , 0.9784771 ],
        [0.07628763, 0.36785328, 0.3362416 ],
        [0.3123387 , 0.0227294 , 0.03754401]],

       ...,

       [[0.374915  , 0.93283474, 0.18005109],
        [0.28

In [145]:
tf.reduce_max(Tens)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9999968>

In [146]:
tf.reduce_min(Tens)

<tf.Tensor: shape=(), dtype=float32, numpy=3.5762787e-07>

In [148]:
tf.random.set_seed(84)

another_T = tf.random.uniform(shape =(1,224,224,3))
another_T.shape

TensorShape([1, 224, 224, 3])

In [149]:
another_T_squeezed = tf.squeeze(another_T)

In [150]:
another_T_squeezed.shape

TensorShape([224, 224, 3])

In [152]:
a_T = tf.random.uniform(shape=[10])
a_T

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.8481529 , 0.28400898, 0.8749603 , 0.26033986, 0.4369836 ,
       0.93344593, 0.04734182, 0.49927986, 0.57824004, 0.2701168 ],
      dtype=float32)>

In [153]:
tf.argmax(a_T)

<tf.Tensor: shape=(), dtype=int64, numpy=5>

In [155]:
a_T.dtype

tf.float32

In [157]:
tf.one_hot(tf.cast(a_T, dtype = tf.int32), depth=10)


<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

done