<a href="https://colab.research.google.com/github/sasumwen/tensorflow-developer-certificate_ZTM/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this Notebook, we cover the most fundamemntal concepts of tensors using tensorFlow 

We cover
* intro to tensors
* getting info from tnesors
* manipulating tensors
* tensors and numpy
* using @tf.function(a way to speed up regular python functions)
* using GPU's with tensorflow(or tpu)
* execrises

## Introduction to Tensors

In [1]:
# import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.9.2


In [3]:
#  Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
#  check the numbr of dimensions of a tensor (ndim stands for number of dimentsions)
scalar.ndim

0

In [6]:
# create a vector tnsor
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
#  check the vect ndim
vector.ndim

1

In [10]:
# create a matric (more than one dimension)
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [11]:
matrix.ndim

2

In [12]:
#  create another matrix
another_one = tf.constant([[10.,7],
                           [3,2],
                           [8,9.]], dtype=tf.float16) # specifying the data type

In [13]:
another_one

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [15]:
another_one.ndim

2