<a href="https://colab.research.google.com/github/sasumwen/tensorflow-developer-certificate_ZTM/blob/next/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this Notebook, we cover the most fundamemntal concepts of tensors using tensorFlow 

We cover
* intro to tensors
* getting info from tnesors
* manipulating tensors
* tensors and numpy
* using @tf.function(a way to speed up regular python functions)
* using GPU's with tensorflow(or tpu)
* execrises

## Introduction to Tensors

In [3]:
# import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.9.2


In [4]:
#  Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
#  check the numbr of dimensions of a tensor (ndim stands for number of dimentsions)
scalar.ndim

0

In [6]:
# create a vector 
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
#  check the vect ndim
vector.ndim

1

In [8]:
# create a matric (more than one dimension)
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
#  create another matrix
another_one = tf.constant([[10.,7],
                           [3,2],
                           [8,9.]], dtype=tf.float16) # specifying the data type

In [11]:
another_one

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [12]:
another_one.ndim

2

In [13]:
#  create a tennsor
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                     [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [14]:
tensor.ndim

3

What we createed so far
* scalar: a single number
* vector: a number with dimension
* matrix:  a 2 dimension array of number
* tensor: an n dimnesion array of number 

# creating tensors with tf.variable

In [15]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

In [16]:
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [17]:
# for variable tensor, you can change the element using the .assign()
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Creating random tensors

In [18]:
# create two random (but same ) tensors
random_1 = tf.random.Generator.from_seed(84) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.65641224, -2.286797  ],
       [ 0.07126775,  2.3546813 ],
       [ 2.2539537 , -0.8510308 ]], dtype=float32)>

### Shuffling the order of elements in a tensor

In [19]:
#  shuffle a tensor (ideal for when you want to shuffle your data so the inherent oredr dossnt affect learning)
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [20]:
tf.random.set_seed(84)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

### Other ways to make tebsors

In [22]:
# Create a tensor of ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [30]:
# create a tensor of all  zeros
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### you can also turn numpy arrays into tensorflow tensors

the amin diff ntw numpy arrays and tensorflow is that tf can be run on a gpu for pfaster computing

In [33]:
import numpy as np
numpy_A = np.arange(1,25, dtype = np.int32) # create a numpy arrays btw 1 and 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [36]:
A = tf.constant(numpy_A, shape= (2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting information from tensorsm=