<a href="https://colab.research.google.com/github/sasumwen/tensorflow-developer-certificate_ZTM/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this Notebook, we cover the most fundamemntal concepts of tensors using tensorFlow 

We cover
* intro to tensors
* getting info from tnesors
* manipulating tensors
* tensors and numpy
* using @tf.function(a way to speed up regular python functions)
* using GPU's with tensorflow(or tpu)
* execrises

## Introduction to Tensors

In [1]:
# import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.9.2


In [2]:
#  Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#  check the numbr of dimensions of a tensor (ndim stands for number of dimentsions)
scalar.ndim

0

In [4]:
# create a vector 
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
#  check the vect ndim
vector.ndim

1

In [6]:
# create a matric (more than one dimension)
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
#  create another matrix
another_one = tf.constant([[10.,7],
                           [3,2],
                           [8,9.]], dtype=tf.float16) # specifying the data type

In [9]:
another_one

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
another_one.ndim

2

In [11]:
#  create a tennsor
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                     [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

What we createed so far
* scalar: a single number
* vector: a number with dimension
* matrix:  a 2 dimension array of number
* tensor: an n dimnesion array of number 

# creating tensors with tf.variable

In [13]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

In [14]:
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [15]:
# for variable tensor, you can change the element using the .assign()
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Creating random tensors

In [16]:
# create two random (but same ) tensors
random_1 = tf.random.Generator.from_seed(84) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.65641224, -2.286797  ],
       [ 0.07126775,  2.3546813 ],
       [ 2.2539537 , -0.8510308 ]], dtype=float32)>

### Shuffling the order of elements in a tensor

In [17]:
#  shuffle a tensor (ideal for when you want to shuffle your data so the inherent oredr dossnt affect learning)
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [18]:
tf.random.set_seed(84)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

### Other ways to make tebsors

In [19]:
# Create a tensor of ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [20]:
# create a tensor of all  zeros
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### you can also turn numpy arrays into tensorflow tensors

the amin diff ntw numpy arrays and tensorflow is that tf can be run on a gpu for pfaster computing

In [21]:
import numpy as np
numpy_A = np.arange(1,25, dtype = np.int32) # create a numpy arrays btw 1 and 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [22]:
A = tf.constant(numpy_A, shape= (2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting information from tensors
* Shape
* Rank
* Axis or dimension
* Size

In [23]:
# create a rank 4 tensor (4 dimension)
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor 

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

### indexing tensors

tensors can be indexed just like python lists

In [24]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [25]:
# get the first element from each dimentsiin from each index except the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [26]:
# create a rank_2 tensor (2 dimension)
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [27]:
# get the last item of each row of the rank2
rank_2_tensor[-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>

In [28]:
# add in extra dimension of rank 2 
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [29]:
# alternatibe to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

## Manipulating tensors(tensor operations)

Basic Ops

In [30]:
# you can add values to a tenssor using the addition operator
tensor = tf.constant([[10,7],
                     [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [31]:
#  multi
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [32]:
#  we can also use the tf built in functions
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [33]:
# or
tf.math.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

### Matrix multiplication

in ML, matrix mult is one of the most common ops

In [34]:
print(tensor)
tf.linalg.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [35]:
# matrix mult using python operator
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [36]:
#  create a a tensor of 3X2
X = tf.constant([[1,2],
                 [3,4],
                [5,6]])

#  another
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [37]:
#  note that the above tensor cant multi 
# refer to matrix mult rules (only when matrix 1 column is equal to matrix 2 row)

# lets reshape tensor Y
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [38]:
#  mult x by reshape(y)
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [39]:
#  can do the same it transpose


** the dot product **
Matrix multiplication  is also referred to as the dot python

can be performed using
* tf.matmul()
* tf.tensordot()

### Changing the data type of a tensor

In [40]:
# create a new tensoor with the deault datatype (float32)
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [41]:
# chanege from float 32 to float 16 (reduce precison)
B = tf.cast(B, dtype=tf.float16)
B


<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

### Aggregating tensors

Aggregating ytensots mean condensing them from multiple vsalurd down to smaller amount of values

In [42]:
# get the absolute values
D =tf.constant([-7, -10])
D, tf.abs(D)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>)

Various forms of aggregaating tensors
* get the minimum
* get the maximum
* get the mean of a tensor
* get the sum of  a tensor


In [43]:
# create a random tensor with values btw 0 and a 100 of size 50
E =tf.constant(np.random.randint(0,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([72,  3, 82, 13, 73, 10, 70, 10, 11, 92, 85, 78, 36, 95, 60, 64, 80,
       65, 26, 73, 55, 62, 79, 87, 93,  7,  6, 34, 84, 28,  3, 80, 37,  8,
       62, 20, 24, 96, 34, 69, 28, 56, 59, 60,  1, 93, 96, 22, 92, 68])>

In [44]:
#  find the min
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [45]:
# find the max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [46]:
# find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [47]:
# find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2641>

In [48]:
# variance
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=964.0276>

In [49]:
# STD
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=31.048794>

### finding the positional max and min

In [50]:
#  create a new tensor for finfing miiiiiiiiiiin anf max
tf.random.set_seed(84)
F = tf.random.uniform(shape=[50])
F


<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6752322 , 0.07654727, 0.17704082, 0.4875176 , 0.59420335,
       0.22550237, 0.9895787 , 0.11397505, 0.76960266, 0.9109514 ,
       0.9022031 , 0.88879526, 0.8251649 , 0.8076726 , 0.37604678,
       0.08291662, 0.08010626, 0.64241993, 0.44362867, 0.54224133,
       0.06212544, 0.49427843, 0.22530258, 0.5357063 , 0.6136848 ,
       0.9981259 , 0.8462304 , 0.0899297 , 0.7671411 , 0.02064371,
       0.17759812, 0.31149256, 0.3833078 , 0.09686565, 0.7968019 ,
       0.73487616, 0.22700477, 0.9049419 , 0.43215597, 0.7176515 ,
       0.57811046, 0.9545188 , 0.9585389 , 0.45191896, 0.60023403,
       0.8077353 , 0.39500773, 0.8875952 , 0.03515244, 0.53597975],
      dtype=float32)>

In [51]:
#  finf the positional max
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=25>

In [52]:
# index on the largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9981259>

In [53]:
# find the max val of F
tf.reduce_max(F)


<tf.Tensor: shape=(), dtype=float32, numpy=0.9981259>

In [54]:
# check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Squeezing a tensor
(removing all single dimensions)

In [55]:
# create a tensor to get startee
tf.random.set_seed(84)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6752322 , 0.07654727, 0.17704082, 0.4875176 , 0.59420335,
           0.22550237, 0.9895787 , 0.11397505, 0.76960266, 0.9109514 ,
           0.9022031 , 0.88879526, 0.8251649 , 0.8076726 , 0.37604678,
           0.08291662, 0.08010626, 0.64241993, 0.44362867, 0.54224133,
           0.06212544, 0.49427843, 0.22530258, 0.5357063 , 0.6136848 ,
           0.9981259 , 0.8462304 , 0.0899297 , 0.7671411 , 0.02064371,
           0.17759812, 0.31149256, 0.3833078 , 0.09686565, 0.7968019 ,
           0.73487616, 0.22700477, 0.9049419 , 0.43215597, 0.7176515 ,
           0.57811046, 0.9545188 , 0.9585389 , 0.45191896, 0.60023403,
           0.8077353 , 0.39500773, 0.8875952 , 0.03515244, 0.53597975]]]]],
      dtype=float32)>

In [56]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6752322 , 0.07654727, 0.17704082, 0.4875176 , 0.59420335,
       0.22550237, 0.9895787 , 0.11397505, 0.76960266, 0.9109514 ,
       0.9022031 , 0.88879526, 0.8251649 , 0.8076726 , 0.37604678,
       0.08291662, 0.08010626, 0.64241993, 0.44362867, 0.54224133,
       0.06212544, 0.49427843, 0.22530258, 0.5357063 , 0.6136848 ,
       0.9981259 , 0.8462304 , 0.0899297 , 0.7671411 , 0.02064371,
       0.17759812, 0.31149256, 0.3833078 , 0.09686565, 0.7968019 ,
       0.73487616, 0.22700477, 0.9049419 , 0.43215597, 0.7176515 ,
       0.57811046, 0.9545188 , 0.9585389 , 0.45191896, 0.60023403,
       0.8077353 , 0.39500773, 0.8875952 , 0.03515244, 0.53597975],
      dtype=float32)>

### onehot encode tensors

In [57]:
# create a list of index
some_list = [0,1,2,3]

# onehot encode
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

### tensors and numpy

tensorflow interacts beautifully woith np arrays


In [58]:
# create a tensor directly from a numpy array
J = tf.constant(np.array([3., 7., 10]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [60]:
# convert the tensor back to np array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [62]:
# convert tensor j tp np
J.numpy()

array([ 3.,  7., 10.])

In [63]:
tf.test.gpu_device_name()


''

In [65]:
tf.config.list_physical_devices(

)

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [66]:
tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

## 00. TensorFlow Fundamentals Exercises

In [60]:
#  create a scalar
S = tf.constant(84)
S

<tf.Tensor: shape=(), dtype=int32, numpy=84>

In [61]:
# create a vector
V = tf.constant([8,4])
V

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([8, 4], dtype=int32)>

In [65]:
# create a matrix
M = tf.constant(
                  [
                    [1,2,3],
                    [4,5,6]
                  ] 
                )
M

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [64]:
# create a tensor
T = tf.constant(
                  [
                      [
                          [1,2,3],
                          [4,5,6],
                          [7,8,9]
                      ],
                      [
                          [10,11,12],
                          [13,14,15],
                          [16,17,18]
                      ]
                  ]
              )
T

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [66]:
# find the shape rank and size of anbove
T.shape, tf.size(T), tf.rank(T)

(TensorShape([2, 3, 3]),
 <tf.Tensor: shape=(), dtype=int32, numpy=18>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>)

In [ ]:
#  create a random tensor withrandom values between 0 and 1 and shape [5,300]
